### ISSUE TITLE
Wrong toppings!

### ISSUE THREAD

**Issue by pizzafan24** [pizzafan24/restaurant-rs#1]
### Why are customers asking for tyre pizzas??

I have been receiving the STRANGEST requests from customers this week after the new PR was merged -- my car is nearly out of wheels!

Our customers are reporting that they are not receiving the toppings that they are ordering. For example, they will select "Sardines" but then our system reports it as "Tyre." Why is this happening? 

These are the toppings we actually offer that should be registered in the system:

1. Pepperoni
2. Sardines
3. Onions
4. Bacon

**Comment by celialewis3** [comment]
Hey! I'm going to pick this issue up!

**Comment by celialewis3** [comment]
Hey! I'm going to tackle this issue.
